sudo:
  false

language:
  php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_script:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-clover=coverage.clover
  - vendor/bin/phpcs --standard=PSR2 src

notifications:
  email: false
